name: CI

on:
    push:
        branches: ["main"]

permissions: write-all
    # actions: write
    # contents: write
    # pages: write
    # id-token: write
    # pull-requests: write
    # deployments: write
    # checks: write
          

jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:

        -   name: Checkout
            uses: actions/checkout@v2

        -   name: Declare Patch Variable
            shell: bash
            run: |
              echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"


        -   name: Set Node.js 18.x
            uses: actions/setup-node@v3
            with:
                node-version: 18.x

        -   name: Run Yarn Install
            uses: borales/actions-yarn@v4
            with:
                cmd: install

        -   name: Build production bundle
            uses: borales/actions-yarn@v4
            with:
                cmd: kbve  
    
        -   name: Pushes test file
            uses: dmnemec/copy_file_to_another_repo_action@main
            env:
                API_TOKEN_GITHUB: ${{ secrets.UNITY_PAT }}
                GITSHA: ${{ github.sha }}
            with:
                source_file: 'yorha-ui'
                destination_repo: 'kbve/kbve.com'
                destination_folder: '/public/embed/'
                destination_branch: 'dev'
                destination_branch_create: 'patch-${{ env.GITSHA }}'
                user_email: 'my-github-actions-bot@example.org'
                user_name: 'My GitHub Actions Bot'
                commit_message: 'Test Casing'

        # -   name: Pushes to another repository
        #     uses: cpina/github-action-push-to-another-repository@main
        #     env:
        #         API_TOKEN_GITHUB: ${{ secrets. }}
        #     with:
        #         source-directory: 'docs'
        #         destination-github-username: 'kbve'
        #         destination-repository-name: 'kbve.com'
        #         user-email: my-github-actions-bot@example.org
        #         target-branch: dev
        #         target-directory: '/public/embed/yorha-ui/'
        #         create-target-branch-if-needed: true
