name: CI

on:
    push:
        branches: ["main"]

jobs:
    copy-file:
        runs-on: ubuntu-latest
        steps:

        -   name: Checkout
            uses: actions/checkout@v3

        -   name: Declare Patch Variable
            shell: bash
            run: |
              echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"


        -   name: Set Node.js 18.x
            uses: actions/setup-node@v3
            with:
                node-version: 18.x

        -   name: Run Yarn Install
            uses: borales/actions-yarn@v4
            with:
                cmd: install

        -   name: Build production bundle
            uses: borales/actions-yarn@v4
            with:
                cmd: kbve  
    
        -   name: Pushes test file
            uses: dmnemec/copy_file_to_another_repo_action@main
            env:
                API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
                GITSHA: ${{ github.sha }}
            with:
                source_file: 'docs'
                destination_repo: 'kbve/kbve.com'
                destination_folder: '/public/embed/yorha-ui/'
                destination_branch: 'dev'
                destination_branch_create: 'patch-${{ env.GITSHA }}'
                user_email: '5599058+h0lybyte@users.noreply.github.com'
                user_name: '[h0lybyteBot]'
                commit_message: 'Test Casing'